packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  cli:
    '@antfu/eslint-config': ^4.13.2
    eslint: ^9.24.0
    lint-staged: ^16.1.0
    simple-git-hooks: ^2.13.0
    typescript: ^5.8.3
    unbuild: ^3.5.0
    vite: ^6.3.5
  testing:
    '@vitest/coverage-v8': ^3.1.4
    vitest: ^3.1.4
    vitest-package-exports: ^0.1.1
  types:
    '@types/node': ^22.15.3
    '@types/qs': ^6.9.18
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
